### ISSUE TITLE
Macros 1.1 as it relates to JSON schema

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/talks#1]
@lylemoffitt I moved this from https://github.com/serde-rs/json/issues/176#issuecomment-269110817 in order to not derail that discussion too much.

> If it's ok, I have some questions about your talk:

> 1. Do you have to use and AST in the middle, or will any old string manipulation work (assuming the result is valid rust code)?

Any old string manipulation will work but I wouldn't recommend it. In theory you could build a procedural macro solely atop `String::find` or `String::contains` but as soon as the input starts getting complicated, you will find yourself doing all of the work that's already been done in an existing AST library.

The other reasonable alternative right now to `syn` is [`syntex`](https://github.com/serde-rs/syntex) but it will take 15x longer to compile for no benefit - the majority of the library is things not relevant to custom derives.

You could ask the same question about building the output. This is slightly more reasonable to do with just ordinary string manipulation. As far as I know, only one library has ever done this: [postgres-derive](https://github.com/sfackler/rust-postgres-derive/blob/ef2c9a88c9665be07f1056423e4701fca2795879/postgres-derive-internals/src/fromsql.rs). It has since been updated to use `quote!` because string manipulation is hard.

> 2. Can I redirect the generated code to another file?

Sure, you are just writing a Rust function so it can have whatever side effects you want.

It gets complicated because the compiler does not guarantee what order your procedural macro will get expanded across all of the structs that it is applied to. In particular you can't assume that they will be expanded top-to-bottom in the file, or inner-to-outer in terms of nesting. In the future they may even be expanded in parallel. So using files won't help you transmit information from one struct to another, you will need to process the files afterward in some way.

> 3. Does the derived source code replace the written code, or just append it?

It just appends new code into the current crate. The written code (i.e. the struct definition that has the derive) is kept in the crate and cannot be modified by the procedural macro.

> 4. Can `quote!` generate further derive attributes or other macro calls that will later be expanded?

Yes. Serde takes advantage of this where our generated code contains `try!` macros. Any derives or macros in the generated code will get expanded recursively.

**Comment by lylemoffitt** [comment]
Follow-ups (corresponding by number):
2) My original intent with this question was more about what requirements there are on the data returned by the proc. macro (my bad); e.g. if I redirect the generated code to another file (and return nothing) what happens? I think you might have provided the answer with Q3, that is, the block referred to the macro stays in the source as-is. Is that correct?
3) Building off of the lack of order guarantees that you mentioned in Q2, would it be correct to say that while the source is appended, it may not directly follow the source it derived from, because it might be interposed by the output of another derive on the same source? 
3) Is this append-nature only true for proc. macros in `derive` or other attributes?  Is the same true for proc. macros that wrap a block of code? I've seen some eDSL libs that wrap what would otherwise be invalid Rust code. Maybe `macro_rules!` does can remove (or comment out) the original source? This append-only thing seems inconsistent; I think I'm missing something here.

---
I also wanted to touch on your response to one of the questions you got. You had said (at 42:30 ish) that you could flag attributes to be ignored by the compiler. How is this set? Are they added by the proc. macro?

**Comment by dtolnay** [comment]
> 2) My original intent with this question was more about what requirements there are on the data returned by the proc. macro (my bad); e.g. if I redirect the generated code to another file (and return nothing) what happens? I think you might have provided the answer with Q3, that is, the block referred to the macro stays in the source as-is. Is that correct?

That is correct.

> 3) Building off of the lack of order guarantees that you mentioned in Q2, would it be correct to say that while the source is appended, it may not directly follow the source it derived from, because it might be interposed by the output of another derive on the same source?

No, during macro expansion the compiler is no longer dealing with the text of the program, it is dealing with its own internal AST. See the phases of compilation in https://github.com/serde-rs/json/issues/176#issuecomment-269099679. It has no concept of the generated piece of code being above or below the original piece of code. In fact it knows that the original code came from a particular spot in the input file and the generated code came from macro expansion i.e. is nowhere in the input file. This is useful for later static analysis, for example you might enforce stricter code style lints on handwritten code compared to generated code because for handwritten code you want the code to be readable, but for generated code you want the generat**ing** code to be readable, not the generat**ed** code.

> 3) Is this append-nature only true for proc. macros in `derive` or other attributes? Is the same true for proc. macros that wrap a block of code? I've seen some eDSL libs that wrap what would otherwise be invalid Rust code. Maybe `macro_rules!` does can remove (or comment out) the original source? This append-only thing seems inconsistent; I think I'm missing something here.

Append-only is for custom derives. The point of derive is to procedurally implement traits/methods/functions for a data structure so it shouldn't have to modify the definition of the data structure.

Other attributes don't come with the same expectation so they are allowed to modify. See [the RFC](https://github.com/rust-lang/rfcs/pull/1566), in particular where it says "The attribute and the AST node it is applied to are both replaced by the returned tokens." That said, I'm pretty sure the input still has to be syntactically valid Rust code, though not necessarily correctly typed. That is because parsing happens before macro expansion and type-checking happens after.

Function-like macros obviously expand into something that replaces the macro invocation.

> You had said (at 42:30 ish) that you could flag attributes to be ignored by the compiler. How is this set? Are they added by the proc. macro?

The proc macro registers itself along with an optional list of attributes that it owns and that it wants the compiler to ignore.

https://github.com/serde-rs/serde/blob/v0.8.21/serde_derive/src/lib.rs#L8

```rust
#[proc_macro_derive(Serialize, attributes(serde))]
pub fn derive_serialize(input: TokenStream) -> TokenStream {
```
